DELETE http://localhost:3001/api/blogs/5f0edb5ec9ca1b0630d168a0
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpIiwiaWQiOiI1ZjBlYjVhOWVlNWRiYzFkNDg3MDQ0YTgiLCJpYXQiOjE1OTQ4MDI4MDB9.7ABWeYkLdWysuiKHHtmqrJY0_xisXtPXFXy0-doLScA

{
  "userId":"5f0eb5a9ee5dbc1d487044a8"
}