PUT http://localhost:3001/api/blogs/5f0eee62b3f932331c81c1e0
Content-Type: application/json

{
  "title":"Changing likes",
  "author": "Teemu testaaja",
  "likes":"444",
  "url":"www.testiurl.com"
  }
